Add Rust examples
hyperledger/iroha-2-examples pull request #22
Opened 2024-06-21 13:15 UTC by nxsaken

This is a draft PR on new Rust SDK examples.

2024-06-24 00:53 UTC, 0x009922 reviewed
New examples look indeed more expressive with a thin higher-level layer. However, I think it is problematic that we will have to introduce readers into these examples-specific abstractions. Although it is now certainly a step towards better examples, I think it is a sign that something like this should be a part of `iroha` library API. In my view, best examples would be "bare", self-contained, and would not require extra layers apart from the target library itself.

2024-06-24 00:53 UTC, 0x009922 commented on Rust/configs/bob_chess.toml
> +private_key = "802640AF3F96DEEF44348FEB516C057558972CEC4C75C4DB9C5B3AAC843668854BF82804FF5B81046DDCCF19E2E451C45DFB6F53759D4EB30FA2EFA807284D1CC33016"
```suggestion
[account]
domain = "chess"
# Bob's key pair
public_key = "ed012004FF5B81046DDCCF19E2E451C45DFB6F53759D4EB30FA2EFA807284D1CC33016"
private_key = "802640AF3F96DEEF44348FEB516C057558972CEC4C75C4DB9C5B3AAC843668854BF82804FF5B81046DDCCF19E2E451C45DFB6F53759D4EB30FA2EFA807284D1CC33016"
```

2024-06-24 00:53 UTC, 0x009922 commented on Rust/examples/account_register.rs
> +    );
- This printing format is convenient for CLI, but is a bit noisy for educational purposes, imo
- Would be useful to see a sample output right here
- In Iroha itself, we recently started to follow a convention of omitting `_id` suffix in most cases

```suggestion
    println!("Account: {}\nRegistered by: {}", account.id, as_who.account);
    // Account: ed12...41@wonderland
    // Registered by: ed01...12@wonderland
```

2024-06-24 14:13 UTC, nxsaken commented
@0x009922 I definitely went overboard with the asset definitions, realized I can remove all that stuff. I guess the pain point that led to this is the lack of const APIs for constructing data primitives.

2024-11-06 06:41 UTC, mversic requested changes

2024-11-06 06:41 UTC, mversic commented on Rust/configs/alice_chess.toml
> +chain = "00000000-0000-0000-0000-000000000000"
we emphasize somewhere in the docs that this value **must be** generated as UUID (and why). This here is just a dummy value

2024-11-06 06:41 UTC, mversic commented on Rust/configs/alice_chess.toml
> +# Domain in which Alice has an authority
what does "has an authority" mean here? I'd rephrase

2024-11-06 12:12 UTC, mversic commented on Rust/examples/account_register.rs
> +    let can_register_accounts_in_chess = CanRegisterAccountInDomain {
```suggestion
    let can_register_accounts_in_chess = CanRegisterAccount {
```

2024-11-06 12:13 UTC, mversic commented on Rust/Cargo.toml
> +iroha_executor_data_model = { git = "https://github.com/hyperledger/iroha.git" }
```suggestion
iroha = { version = "=2.0.0-rc.1.0", git = "https://github.com/hyperledger/iroha.git" }
iroha_executor_data_model = { version = "=2.0.0-rc.1.0", git = "https://github.com/hyperledger/iroha.git" }
```

2024-11-06 12:13 UTC, mversic commented on Rust/Cargo.toml
> +iroha_executor_data_model = { git = "https://github.com/hyperledger/iroha.git" }
until we publish on `crates.io`

2024-11-06 12:14 UTC, mversic commented on Rust/examples/account_register.rs
> +    let can_register_accounts_in_chess = CanRegisterAccountInDomain {
if you run `cargo check` this should fail

2024-11-06 12:14 UTC, mversic commented on Rust/examples/account_unregister.rs
> +    println!("Account: {}\nUnregistered by: {}", account, as_who.account);
```suggestion
    println!("Account: {account}\nUnregistered by: {as_who.account}");
```

2024-11-14 15:48 UTC, dima74 commented on Rust/examples/asset_definition_register.rs
> +    let asset_definition_id = asset_definition.id().clone();
This currently doesn't compile, getters should be added to `NewAssetDefinition`

2024-11-15 10:54 UTC, dima74 commented on Rust/examples/asset_definition_register.rs
> +    let asset_definition_id = asset_definition.id().clone();
Fixed by using `Identifiable` trait

2025-03-17 10:24 UTC, closed without merging